# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ridgeway Hugo"
license = "MIT"
version = "0.0.1"
licenselink = "https://github.com/nndi-oss/hugo-ridgeway/main/LICENSE.md"
description = "ridgeway theme for Hugo for NNDI"
homepage = "https://github.com/nndi-oss/ridgeway"
tags = ["responsive", "ridgeway", "documentation", "landing", "blog", "themes", "professional", "modern"]
features = ["Minimalism","Mobile-first Design",
  "Responsive Design",
  "Horizontal Rhythm",
  "Typography",
  "Google Analytics",
  "Disqus Commenting",
  "OpenGraph support",
  "Schema Structured Data",
  "Paginated Lists",
  "Reading Time",
  "Last Modified time",
  "Word Count",
  "Related Posts",
  "Block Templates",
  "Table of Contents",
  "SEO Site Verification"]
[module]
  [module.hugoVersion]
    extended = false
    min = "0.84.0"
[author]
  name = "zikani03"
  homepage = "https://zikani.me/"
 